### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by thecodeduchess** [hartfib/bwa-u4-feature-request#1]
**Grade: Meets Expectations**

**Summary:** 

Caveat section seems to be missing. You did not have any disadvantages or cons to the implementation of the new search feature? Well, you can say that in this section too. lol. 

You lay out a rock solid plan for implementing a feature that definitely improves the user’s Jammming experience. The idea itself is a natural suggestion, as most users would likely assume the Enter key would serve that purpose and therefore would find it inconvenient that the app doesn’t do that. Your implementation is also the easiest way to accomplish the goal. 

I thought the technical design was outstanding and detailed instructions on implementation. Nice work!

**Comment by hartfib** [comment]
Awesome!!  Thank you for the review.  I wasn't sure how to write a technical document and yes, I didn't think about putting in the caveat section that there are not disadvantages.
